import { Stage, Container, Sprite, Text } from '@pixi/react';

export const Pixi = () =>
{
    return (
        <Stage options={{background: 'white'}}>
            <Container x={350} y={200}>
                <Container x={0} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={0} y={60}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={200} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={200} y={60}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
            </Container>
            <Container x={350} y={50}>
                <Container x={0} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={0} y={60}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={200} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
                <Container x={200} y={60}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={30}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={60}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={90}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={120}
                        y={0}
                    />
                </Container>
            </Container>
            <Container x={350} y={350}>
                <Container x={0} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={50}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={100}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={150}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={200}
                    />
                </Container>
                <Container x={100} y={0}>
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={0}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={50}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={100}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={150}
                    />
                    <Sprite
                        image="https://pixijs.io/pixi-react/img/bunny.png"
                        x={0}
                        y={200}
                    />
                </Container>
            </Container>
        </Stage>
    );
};